enum DataleonFlowStep {
  loading,
  alreadyProcessed,
  error,
  welcome,
  cameraPermission,
  documentType,
  documentCountry,
  document,
  chainedDocumentIntro,
  chainedCustomDocument,
  selfie,
  review,
  submitting,
  success,
}
